#!/usr/bin/env bash
#
# Regenerate the Python lock from the environment Ren was MEASURED on.
#
#     scripts/lock_python_env.sh                    # the shared venv
#     scripts/lock_python_env.sh --python <python>  # another interpreter
#
# requirements.txt (and the group files it includes) is the compatibility
# POLICY: floors, ceilings and why. The lock is the INSTRUMENT: the exact
# Apple-Silicon stack those measurements were taken on, with hashes, so a
# new machine reproduces it instead of whatever the floors resolve to that
# day:
#
#     uv venv --python 3.12 ~/.local/share/vep/venv-py312
#     uv pip sync --python ~/.local/share/vep/venv-py312/bin/python3 \
#         requirements/lock/macos-arm64-py312.txt
#
# HOW: the venv's installed versions are frozen and used as CONSTRAINTS
# on a fresh resolve of requirements.txt for macOS arm64 / CPython 3.12.
# So every locked version is the one the venv carries, and a venv that
# violates the policy FAILS the resolve rather than being locked. Packages
# the venv carries that nothing declared are left out - the lock is the
# declared closure, not the venv's history.
#
# Run it after the venv changes on purpose (a floor raised, a package
# added), commit the lock with the requirements change, and say in the PR
# what was measured on it. Needs `uv`. Writes only the lock file.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCK="requirements/lock/macos-arm64-py312.txt"
# onnxruntime's arm64 wheels start at macOS 14; the lock is installable
# from there up.
MACOS_TARGET="14.0"

PYTHON=""
while [ $# -gt 0 ]; do
  case "$1" in
    --python) PYTHON="$2"; shift 2 ;;
    -h|--help) sed -n '2,27p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

if [ -z "$PYTHON" ]; then
  # The same ladder bin/vep and `ren doctor` resolve through.
  PYTHON="$(cd "$REPO_ROOT" && python3 -c \
    'from library.tools.shared_environment import python_interpreter as p; i, why = p(); print(i or "")')"
  if [ -z "$PYTHON" ]; then
    echo "no pipeline interpreter found; build one (docs/ML_ENVIRONMENT.md) or pass --python" >&2
    exit 1
  fi
fi

version="$("$PYTHON" -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
if [ "$version" != "3.12" ]; then
  echo "$PYTHON is Python $version; the lock is for 3.12 (requirements/analysis.txt says why)" >&2
  exit 1
fi

scratch="$(mktemp -d)"
trap 'rm -rf "$scratch"' EXIT
uv pip freeze --python "$PYTHON" --exclude-editable > "$scratch/measured.txt"

cd "$REPO_ROOT"
MACOSX_DEPLOYMENT_TARGET="$MACOS_TARGET" uv pip compile requirements.txt \
  --constraints "$scratch/measured.txt" \
  --python-version 3.12 \
  --python-platform aarch64-apple-darwin \
  --generate-hashes \
  --no-header \
  --quiet \
  --output-file "$scratch/lock.txt"

{
  echo "# The measured Apple-Silicon stack: macOS ${MACOS_TARGET}+ arm64, CPython 3.12."
  echo "# GENERATED by scripts/lock_python_env.sh from the venv at"
  echo "# $(dirname "$(dirname "$PYTHON")" | sed "s#^$HOME#~#") - do not edit by hand."
  echo "# The policy is requirements.txt; install this with \`uv pip sync\`."
  # The constraints file is a scratch path; name what it was instead.
  sed "s#-c $scratch/measured.txt#-c (the measured venv)#" "$scratch/lock.txt"
} > "$LOCK"

echo "wrote $LOCK: $(grep -c '^[A-Za-z0-9]' "$LOCK") packages, pinned from $PYTHON"
