"""Build Ren's immutable engine tree: what ships inside a version.

A versioned engine directory holds everything a run reads - and
nothing a run writes:

    <engine>/
        ren/                    the front door (`ren.cli`, `--version`,
                                the engine-root resolver)
        library/                the pipeline (steps, tools, processes
                                with their dag.json/manifest.json,
                                schemas, presets, skills)
        manage_project.py       the engine CLI underneath `ren`
        bin/ren                 the packaged front door
        bin/vep                 the interpreter wrapper
        requirements/           the declared dependency groups
        scripts/                the runtime assets refusals name
                                (`install_*.sh`, ...)
        remotion-subtitles/     renderer SOURCE only - its `node_modules`
                                stays in the shared per-machine store
                                (`shared_environment.py`), never here
        .agents/skills/         the model-facing skill texts
        docs/                   the procedures refusals cite
                                (`ML_ENVIRONMENT.md`, ...)
        pyproject.toml README.md
                                the build declaration and the manual

`ren/_build.py` (generated, never committed - see `.gitignore`) is
written into the BUILT tree only, so `ren --version` off it names its
commit, channel and build date.

`--dest` builds one flat tree (the proof path: point
`$REN_ENGINE_ROOT` at it and run `ren` with no checkout on the
path). `--home` builds in a temporary sibling directory, moves the
complete tree into `<home>/versions/<version>/`, then atomically switches
`<home>/current` onto it - the layout the audit proposes, on
`PIPELINE_VEP_HOME` (`shared_environment.vep_home()`). A version directory
is immutable: an existing version always refuses, so a failed build
cannot damage the active tree.

Out of scope here (queued separately): the end-user installer, the
upgrade/rollback commands, the release workflow and signing.
"""

from __future__ import annotations

import argparse
import datetime
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

#: Directories copied whole (minus the generated/ignored names in
#: `_ignore`). Each is read at runtime from the engine root; each
#: omission would be a file the tree cannot run without.
COPY_DIRS = (
    "ren",
    "library",
    "bin",
    "requirements",
    "scripts",
    "remotion-subtitles",
    ".agents/skills",
    "docs",
)

#: Single files copied beside them.
COPY_FILES = (
    "manage_project.py",
    "pyproject.toml",
    "README.md",
    "THIRD_PARTY_NOTICES",
)

#: Entries that may be absent on older checkouts: copied when present,
#: never required.
OPTIONAL = ()

_GENERATED_NAMES = ("__pycache__", "node_modules", ".DS_Store", ".pytest_cache")
_GENERATED_SUFFIXES = (".pyc", ".pyo")


def _ignore(dirpath: str, names: list) -> list:
    """Leave generated bytes out of the tree: caches, bytecode, the
    shared `node_modules` (per-machine store, never shipped), and the
    per-video generated Remotion props beside the bundled fonts."""
    ignored = [
        name for name in names
        if name in _GENERATED_NAMES or name.endswith(_GENERATED_SUFFIXES)
    ]
    if f"remotion-subtitles{os.sep}public" in dirpath:
        ignored += [name for name in names if name.endswith("Props.json")]
    return ignored


def _src_version(src: Path) -> str:
    """The version this tree ships: the checkout's one source."""
    sys.path.insert(0, str(src))
    try:
        from ren.version import __version__
        return __version__
    finally:
        try:
            sys.path.remove(str(src))
        except ValueError:
            pass


def _src_sha(src: Path) -> str:
    try:
        done = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            capture_output=True, encoding="utf-8", timeout=10, check=False,
            cwd=str(src))
    except (OSError, subprocess.SubprocessError):
        return ""
    return done.stdout.strip() if done.returncode == 0 else ""


def _write_build_record(dest: Path, sha: str, channel: str, built_at: str) -> None:
    dest.joinpath("ren/_build.py").write_text(
        '"""Generated by `ren/package_engine.py` - never committed (see .gitignore).\n'
        '\n'
        'The packaged build record `ren/version.py` reads. A checkout run\n'
        'has no such file and reports itself as an unbuilt `dev` build.\n'
        '"""\n'
        "\n"
        f"BUILD_SHA = {sha!r}\n"
        f"BUILD_DATE = {built_at!r}\n"
        f"BUILD_CHANNEL = {channel!r}\n",
        encoding="utf-8")


def _check(src: Path) -> None:
    missing = [entry for entry in (*COPY_DIRS, *COPY_FILES)
               if entry not in OPTIONAL and not (src / entry).exists()]
    if missing:
        raise RuntimeError(
            f"refusing to package {src}: these engine entries are absent: "
            f"{', '.join(missing)}")


def build_engine_tree(src: Path, dest: Path, channel: str = "dev",
                      sha: str | None = None,
                      built_at: str | None = None) -> Path:
    """Copy the engine entries of `src` into `dest`; return `dest`.

    Refuses when `dest` is non-empty (a version directory is never
    modified in place) and when `dest` sits inside `src`.
    """
    src = src.resolve()
    dest = dest.resolve() if dest.exists() else dest.absolute()
    if src == dest or src in dest.parents:
        raise RuntimeError(
            f"refusing to build {dest} inside its own source {src}: "
            f"point --dest outside the checkout.")
    if dest.exists() and any(dest.iterdir()):
        raise RuntimeError(
            f"refusing to build into non-empty {dest}: a built tree is "
            f"immutable - remove it or build elsewhere.")
    _check(src)
    from ren.version import format_version
    build_sha = sha if sha is not None else _src_sha(src)
    build_date = (built_at if built_at is not None
                  else datetime.date.today().isoformat())
    format_version({
        "version": _src_version(src),
        "sha": build_sha,
        "channel": channel,
        "built_at": build_date,
    })
    dest.mkdir(parents=True, exist_ok=True)
    for entry in COPY_DIRS:
        target = src / entry
        if not target.exists():
            if entry in OPTIONAL:
                continue
            raise RuntimeError(f"refusing to package {src}: {entry} is absent")
        if target.is_dir():
            shutil.copytree(target, dest / entry, ignore=_ignore,
                            symlinks=False)
        else:
            shutil.copy2(target, dest / entry)
    for entry in COPY_FILES:
        target = src / entry
        if not target.exists():
            if entry in OPTIONAL:
                continue
            raise RuntimeError(f"refusing to package {src}: {entry} is absent")
        shutil.copy2(target, dest / entry)
    _write_build_record(
        dest,
        build_sha,
        channel,
        build_date)
    return dest


def version_dir(home: Path, version: str) -> Path:
    """`<home>/versions/<version>`: where this immutable build installs."""
    from ren.engine_root import versions_root
    return versions_root(home) / version


def switch_current(home: Path, version: str) -> Path:
    """Atomically point `<home>/current` at `versions/<version>`.

    The new symlink is built aside and moved over the old one with
    `os.replace`, so a reader never sees a half-written pointer. The
    target is RELATIVE (`versions/<ver>`), so the home relocates.
    """
    from ren.engine_root import current_link, is_engine_root, versions_root
    home = home.expanduser()
    target_dir = versions_root(home) / version
    if not is_engine_root(target_dir):
        raise RuntimeError(
            f"refusing to switch {home}/current onto {version}: "
            f"{target_dir} holds no complete engine tree. "
            f"Install it first.")
    link = current_link(home)
    tmp = link.parent / f".current.{os.getpid()}.tmp"
    try:
        if tmp.is_symlink() or tmp.exists():
            tmp.unlink()
        tmp.symlink_to(Path("versions") / version)
        os.replace(tmp, link)
    finally:
        if tmp.is_symlink():
            tmp.unlink()
    return link


def install_versioned(home: Path, src: Path, channel: str = "stable",
                      sha: str | None = None,
                      built_at: str | None = None) -> Path:
    """Build `<home>/versions/<version>/` from `src` and switch `current`.

    The complete tree moves into place before the current pointer changes.
    A version directory is immutable: if it already exists, refuse without
    touching it or the current pointer.
    """
    home = home.expanduser()
    from ren.version import format_version
    version = _src_version(src)
    build_sha = sha if sha is not None else _src_sha(src)
    build_date = (built_at if built_at is not None
                  else datetime.date.today().isoformat())
    build_id = format_version({
        "version": version,
        "sha": build_sha,
        "channel": channel,
        "built_at": build_date,
    })
    dest = version_dir(home, build_id)
    if dest.exists():
        raise RuntimeError(
            f"refusing to rebuild {dest}: a version directory is immutable. "
            f"Choose a new version or remove an unreferenced incomplete "
            f"directory manually.")

    versions = dest.parent
    versions.mkdir(parents=True, exist_ok=True)
    staging_parent = Path(tempfile.mkdtemp(
        prefix=f".{version}.", suffix=".staging", dir=str(versions)))
    staged = staging_parent / "engine"
    try:
        build_engine_tree(src, staged, channel=channel, sha=build_sha,
                          built_at=build_date)
        # Catch a concurrent install before publishing the completed tree.
        if dest.exists():
            raise RuntimeError(
                f"refusing to publish {dest}: that version appeared while "
                f"the engine was being built.")
        os.rename(staged, dest)
    finally:
        shutil.rmtree(staging_parent, ignore_errors=True)

    switch_current(home, build_id)
    return dest


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="ren package-engine", description=__doc__.splitlines()[0])
    parser.add_argument("--src", default=".",
                        help="The checkout to package (default: cwd)")
    targets = parser.add_mutually_exclusive_group(required=True)
    targets.add_argument("--dest",
                         help="Build one flat engine tree here")
    targets.add_argument("--home",
                         help="Install versioned into this home "
                              "(<home>/versions/<ver>/ + current pointer)")
    parser.add_argument("--channel", default="dev",
                        help="Release channel baked into the build "
                             "record (default: dev)")
    parser.add_argument("--sha", default=None,
                        help="Commit baked into the build record "
                             "(default: the checkout's HEAD)")
    parser.add_argument("--built-at", default=None,
                        help="Build date baked into the record "
                             "(default: today)")
    args = parser.parse_args(argv)

    src = Path(args.src).expanduser().resolve()
    try:
        if args.home:
            dest = install_versioned(
                Path(args.home).expanduser(), src,
                channel=args.channel, sha=args.sha,
                built_at=args.built_at)
            print(f"installed {dest} and switched current onto it")
        else:
            dest = build_engine_tree(
                src, Path(args.dest).expanduser(),
                channel=args.channel, sha=args.sha,
                built_at=args.built_at)
            print(f"built engine tree at {dest}")
    except (RuntimeError, ValueError) as exc:
        print(f"ren package-engine: refused - {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
