"""Build Ren's immutable engine tree: what ships inside a version.

A versioned engine directory holds everything a run reads - and
nothing a run writes:

    <engine>/
        ren/                    the front door (`ren.cli`, `--version`,
                                the engine-root resolver)
        library/                the pipeline (steps, tools, processes
                                with their dag.json/manifest.json,
                                schemas, presets, skills)
        manage_project.py       the engine CLI underneath `ren`
        bin/ren                 the packaged front door
        bin/vep                 the interpreter wrapper
        requirements/           the declared dependency groups
        scripts/                the runtime assets refusals name
                                (`install_*.sh`, ...)
        remotion-subtitles/     renderer SOURCE only - its `node_modules`
                                stays in the shared per-machine store
                                (`shared_environment.py`), never here
        hyperframes/            public renderer templates and vendored GSAP
        .agents/skills/         the model-facing skill texts
        docs/                   the procedures refusals cite
                                (`ML_ENVIRONMENT.md`, ...)
        pyproject.toml README.md
                                the build declaration and the manual

`ren/_build.py` (generated, never committed - see `.gitignore`) is
written into the BUILT tree only, so `ren --version` off it names its
commit, channel and build date.

`--dest` builds one flat tree (the proof path: point
`$REN_ENGINE_ROOT` at it and run `ren` with no checkout on the
path). `--home` builds in a temporary sibling directory, moves the
complete tree into `<home>/versions/<version>/`, then atomically switches
`<home>/current` onto it - the layout the audit proposes, on
`PIPELINE_VEP_HOME` (`shared_environment.vep_home()`). A version directory
is immutable: an existing version always refuses, so a failed build
cannot damage the active tree.

The end-user installer, release workflow and signing remain separate.
"""

from __future__ import annotations

import argparse
import ast
import datetime
import functools
import os
import shutil
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path

#: Directories copied whole (minus the generated/ignored names in
#: `_ignore`). Each is read at runtime from the engine root; each
#: omission would be a file the tree cannot run without.
COPY_DIRS = (
    "ren",
    "library",
    "bin",
    "requirements",
    "scripts",
    "remotion-subtitles",
    "hyperframes",
    ".agents/skills",
    "docs",
)

#: Single files copied beside them.
COPY_FILES = (
    "manage_project.py",
    "pyproject.toml",
    "README.md",
    "THIRD_PARTY_NOTICES",
)

#: Entries that may be absent on older checkouts: copied when present,
#: never required.
OPTIONAL = ()

_GENERATED_NAMES = ("__pycache__", "node_modules", ".DS_Store", ".pytest_cache")
_GENERATED_SUFFIXES = (".pyc", ".pyo")


def _ignore(dirpath: str, names: list, *, source_root: Path,
            blocked: frozenset[str] = frozenset()) -> list:
    """Leave generated bytes out of the tree: caches, bytecode, the
    shared `node_modules` (per-machine store, never shipped), and the
    per-video generated Remotion props beside the bundled fonts."""
    ignored = [
        name for name in names
        if name in _GENERATED_NAMES or name.endswith(_GENERATED_SUFFIXES)
    ]
    parent = Path(dirpath)
    try:
        relative_parent = parent.relative_to(source_root).as_posix()
    except ValueError:
        relative_parent = ""
    for name in names:
        relative = (Path(relative_parent) / name).as_posix()
        if relative in blocked or any(
                relative.startswith(f"{path}/") for path in blocked):
            ignored.append(name)
    if f"remotion-subtitles{os.sep}public" in dirpath:
        ignored += [name for name in names if name.endswith("Props.json")]
    return ignored


def _src_version(src: Path) -> str:
    """Read the version from `src`, even when another Ren is imported.

    Importing `ren.version` here reused the already-loaded package when
    upgrading from a different checkout, silently rebuilding the active
    version. Parsing the literal avoids executing candidate code and
    keeps the source checkout as the authority.
    """
    values = _literal_assignments(src / "ren" / "version.py", {"__version__"})
    version = values.get("__version__")
    if not isinstance(version, str):
        raise RuntimeError(
            f"refusing to package {src}: ren/version.py must declare a "
            "literal string __version__.")
    return version


def _literal_assignments(path: Path, names: set[str]) -> dict:
    """Read selected module-level literal assignments without executing them."""
    try:
        module = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except (OSError, SyntaxError) as exc:
        raise RuntimeError(f"cannot read build metadata from {path}: {exc}") from exc
    values = {}
    for node in module.body:
        if isinstance(node, ast.Assign):
            targets = node.targets
            value = node.value
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
            value = node.value
        else:
            continue
        for target in targets:
            if isinstance(target, ast.Name) and target.id in names:
                try:
                    values[target.id] = ast.literal_eval(value)
                except (ValueError, TypeError):
                    continue
    return values


def _src_build_info(src: Path) -> dict:
    """Read a packaged source tree's generated build identity, if present."""
    path = src / "ren" / "_build.py"
    if not path.is_file():
        return {}
    raw = _literal_assignments(
        path, {"BUILD_SHA", "BUILD_DATE", "BUILD_CHANNEL"})
    return {
        "sha": raw.get("BUILD_SHA", ""),
        "built_at": raw.get("BUILD_DATE", ""),
        "channel": raw.get("BUILD_CHANNEL", ""),
    }


def _src_sha(src: Path) -> str:
    try:
        done = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            capture_output=True, encoding="utf-8", timeout=10, check=False,
            cwd=str(src))
    except (OSError, subprocess.SubprocessError):
        return ""
    return done.stdout.strip() if done.returncode == 0 else ""


def _write_build_record(dest: Path, sha: str, channel: str, built_at: str,
                        edition: str) -> None:
    dest.joinpath("ren/_build.py").write_text(
        '"""Generated by `ren/package_engine.py` - never committed (see .gitignore).\n'
        '\n'
        'The packaged build record `ren/version.py` reads. A checkout run\n'
        'has no such file and reports itself as an unbuilt `dev` build.\n'
        '"""\n'
        "\n"
        f"BUILD_SHA = {sha!r}\n"
        f"BUILD_DATE = {built_at!r}\n"
        f"BUILD_CHANNEL = {channel!r}\n"
        f"BUILD_EDITION = {edition!r}\n",
        encoding="utf-8")


def _check(src: Path) -> None:
    missing = [entry for entry in (*COPY_DIRS, *COPY_FILES)
               if entry not in OPTIONAL and not (src / entry).exists()]
    if missing:
        raise RuntimeError(
            f"refusing to package {src}: these engine entries are absent: "
            f"{', '.join(missing)}")


def _safe_path(value: str, *, field: str) -> Path:
    path = Path(value)
    if path.is_absolute() or ".." in path.parts:
        raise RuntimeError(f"unsafe {field} in component inventory: {value!r}")
    return path


def _edition_policy(src: Path, edition: str) -> tuple[set[str], set[str], dict[str, set[str]], list[tuple[str, str]]]:
    """Return files/directories, installer files, requirement filters and copies.

    The component inventory is the one place that says which bytes and
    dependencies are personal-only. A public build filters those entries
    before writing its immutable tree.
    """
    from ren.edition import PERSONAL_ONLY, read_components

    components = read_components(src)
    blocked_paths: set[str] = set()
    blocked_installers: set[str] = set()
    requirement_filters: dict[str, set[str]] = {}
    copies: list[tuple[str, str]] = []
    for entry in components.values():
        if edition == "public" and entry.edition == PERSONAL_ONLY:
            for value in entry.package_paths:
                blocked_paths.add(_safe_path(value, field="package-path").as_posix())
            for value in entry.installer_paths:
                blocked_installers.add(
                    _safe_path(value, field="installer-path").as_posix())
            for requirement_file, package in entry.requirement_refs:
                requirement_path = _safe_path(
                    requirement_file, field="requirement-ref").as_posix()
                requirement_filters.setdefault(requirement_path, set()).add(package)
        for source, destination in entry.package_copies:
            copies.append((
                _safe_path(source, field="package-copy source").as_posix(),
                _safe_path(destination, field="package-copy destination").as_posix(),
            ))
    return blocked_paths, blocked_installers, requirement_filters, copies


def _without_requirements(text: str, names: set[str]) -> str:
    """Remove active requirement lines by normalized package name."""
    import re

    blocked = {re.sub(r"[-_.]+", "-", name).lower() for name in names}
    kept = []
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        if not stripped or stripped.startswith(("#", "-", "\\")):
            kept.append(line)
            continue
        candidate = stripped.split("#", 1)[0].strip()
        package = re.split(r"[<>=!~;\s\[]", candidate, maxsplit=1)[0]
        normalized = re.sub(r"[-_.]+", "-", package).lower()
        if normalized not in blocked:
            kept.append(line)
    return "".join(kept)


def build_engine_tree(src: Path, dest: Path, channel: str = "dev",
                      sha: str | None = None,
                      built_at: str | None = None,
                      edition: str | None = None) -> Path:
    """Copy the engine entries of `src` into `dest`; return `dest`.

    Refuses when `dest` is non-empty (a version directory is never
    modified in place) and when `dest` sits inside `src`.
    """
    src = src.resolve()
    dest = dest.resolve() if dest.exists() else dest.absolute()
    if src == dest or src in dest.parents:
        raise RuntimeError(
            f"refusing to build {dest} inside its own source {src}: "
            f"point --dest outside the checkout.")
    if dest.exists() and any(dest.iterdir()):
        raise RuntimeError(
            f"refusing to build into non-empty {dest}: a built tree is "
            f"immutable - remove it or build elsewhere.")
    _check(src)
    from ren.edition import _normalise_edition, current_edition

    selected_edition = (_normalise_edition(edition) if edition is not None
                        else current_edition(src))
    blocked_paths, blocked_installers, requirement_filters, package_copies = (
        _edition_policy(src, selected_edition))
    from ren.version import format_version
    build_sha = sha if sha is not None else _src_sha(src)
    build_date = (built_at if built_at is not None
                  else datetime.date.today().isoformat())
    format_version({
        "version": _src_version(src),
        "sha": build_sha,
        "channel": channel,
        "edition": selected_edition,
        "built_at": build_date,
    })
    dest.mkdir(parents=True, exist_ok=True)
    for entry in COPY_DIRS:
        target = src / entry
        relative = Path(entry).as_posix()
        if relative in blocked_paths or any(
                relative.startswith(f"{path}/") for path in blocked_paths):
            continue
        if not target.exists():
            if entry in OPTIONAL:
                continue
            raise RuntimeError(f"refusing to package {src}: {entry} is absent")
        if target.is_dir():
            ignored = blocked_installers | blocked_paths
            ignore = functools.partial(
                _ignore, source_root=src, blocked=frozenset(ignored))
            shutil.copytree(target, dest / entry, ignore=ignore,
                            symlinks=False)
        else:
            shutil.copy2(target, dest / entry)
    for entry in COPY_FILES:
        target = src / entry
        relative = Path(entry).as_posix()
        if not target.exists():
            if entry in OPTIONAL:
                continue
            raise RuntimeError(f"refusing to package {src}: {entry} is absent")
        if relative not in blocked_paths and relative not in blocked_installers:
            shutil.copy2(target, dest / entry)
    for requirement_file, names in requirement_filters.items():
        destination = dest / requirement_file
        if not destination.is_file():
            continue
        destination.write_text(
            _without_requirements(
                destination.read_text(encoding="utf-8"), names),
            encoding="utf-8")
    for source, destination in package_copies:
        source_path = src / source
        if not source_path.is_file():
            raise RuntimeError(
                f"refusing to package {source_path}: component inventory "
                "package-copy source is missing")
        destination_path = dest / destination
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination_path)
    _write_build_record(
        dest,
        build_sha,
        channel,
        build_date,
        selected_edition)
    return dest


def version_dir(home: Path, version: str) -> Path:
    """`<home>/versions/<version>`: where this immutable build installs."""
    from ren.engine_root import versions_root
    return versions_root(home) / version


def switch_current(home: Path, version: str) -> Path:
    """Atomically point `<home>/current` at `versions/<version>`.

    The new symlink is built aside and moved over the old one with
    `os.replace`, so a reader never sees a half-written pointer. The
    target is RELATIVE (`versions/<ver>`), so the home relocates.
    """
    return _switch_pointer(home, "current", version)


def switch_previous(home: Path, version: str) -> Path:
    """Atomically point `<home>/previous` at a complete version."""
    return _switch_pointer(home, "previous", version)


def _switch_pointer(home: Path, name: str, version: str) -> Path:
    from ren.engine_root import (
        current_link, is_engine_root, previous_link, versions_root,
    )
    home = home.expanduser()
    if (not isinstance(version, str) or not version
            or Path(version).name != version or version in {".", ".."}):
        raise RuntimeError(f"refusing an invalid engine version name: {version!r}")
    target_dir = versions_root(home) / version
    if not is_engine_root(target_dir):
        raise RuntimeError(
            f"refusing to switch {home}/{name} onto {version}: "
            f"{target_dir} holds no complete engine tree. "
            f"Install it first.")
    link = current_link(home) if name == "current" else previous_link(home)
    home.mkdir(parents=True, exist_ok=True)
    if (link.exists() or link.is_symlink()) and not link.is_symlink():
        raise RuntimeError(
            f"refusing to replace {link}: it exists and is not a symlink.")
    tmp = link.parent / f".{name}.{os.getpid()}.{uuid.uuid4().hex}.tmp"
    try:
        if tmp.exists() or tmp.is_symlink():
            raise RuntimeError(f"refusing to replace unexpected temporary {tmp}")
        tmp.symlink_to(Path("versions") / version)
        os.replace(tmp, link)
    finally:
        if tmp.is_symlink():
            tmp.unlink()
    return link


def stage_versioned(home: Path, src: Path, channel: str | None = None,
                    sha: str | None = None,
                    built_at: str | None = None,
                    edition: str | None = None) -> Path:
    """Build and publish one immutable version without switching `current`.

    The complete tree is moved into place only after it builds. The caller
    can then inspect it before making it active. Existing versions always
    refuse rather than being changed in place.
    """
    home = home.expanduser()
    src = Path(src).expanduser().resolve()
    source_info = _src_build_info(src)
    from ren.version import format_version
    from ren.edition import _normalise_edition, current_edition

    selected_edition = (_normalise_edition(edition) if edition is not None
                        else current_edition(src))
    version = _src_version(src)
    build_sha = (sha if sha is not None else
                 (_src_sha(src) or source_info.get("sha", "")))
    build_channel = channel or source_info.get("channel", "") or "stable"
    build_date = (built_at if built_at is not None else
                  (source_info.get("built_at", "")
                   or datetime.date.today().isoformat()))
    build_id = format_version({
        "version": version,
        "sha": build_sha,
        "channel": build_channel,
        "edition": selected_edition,
        "built_at": build_date,
    })
    dest = version_dir(home, build_id)
    if dest.exists():
        raise RuntimeError(
            f"refusing to rebuild {dest}: a version directory is immutable. "
            f"Choose a new version or remove an unreferenced incomplete "
            f"directory manually.")

    versions = dest.parent
    versions.mkdir(parents=True, exist_ok=True)
    staging_parent = Path(tempfile.mkdtemp(
        prefix=f".{version}.", suffix=".staging", dir=str(versions)))
    staged = staging_parent / "engine"
    try:
        build_engine_tree(src, staged, channel=build_channel, sha=build_sha,
                          built_at=build_date, edition=selected_edition)
        # Catch a concurrent install before publishing the completed tree.
        if dest.exists():
            raise RuntimeError(
                f"refusing to publish {dest}: that version appeared while "
                f"the engine was being built.")
        os.rename(staged, dest)
    finally:
        shutil.rmtree(staging_parent, ignore_errors=True)

    return dest


def install_versioned(home: Path, src: Path, channel: str | None = "stable",
                      sha: str | None = None,
                      built_at: str | None = None,
                      edition: str | None = None) -> Path:
    """Build `<home>/versions/<version>/` from `src` and activate it.

    The complete immutable tree is published before the atomic current
    pointer changes. A duplicate version refuses without touching the
    active pointer.
    """
    dest = stage_versioned(home, src, channel=channel, sha=sha,
                           built_at=built_at, edition=edition)
    switch_current(home, dest.name)
    return dest


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="ren package-engine", description=__doc__.splitlines()[0])
    parser.add_argument("--src", default=".",
                        help="The checkout to package (default: cwd)")
    targets = parser.add_mutually_exclusive_group(required=True)
    targets.add_argument("--dest",
                         help="Build one flat engine tree here")
    targets.add_argument("--home",
                         help="Install versioned into this home "
                              "(<home>/versions/<ver>/ + current pointer)")
    parser.add_argument("--channel", default="dev",
                        help="Release channel baked into the build "
                             "record (default: dev)")
    parser.add_argument("--edition", choices=("public", "personal"),
                        default=None,
                        help="Product edition to build (default: $REN_EDITION "
                             "or personal for an unconfigured checkout)")
    parser.add_argument("--sha", default=None,
                        help="Commit baked into the build record "
                             "(default: the checkout's HEAD)")
    parser.add_argument("--built-at", default=None,
                        help="Build date baked into the record "
                             "(default: today)")
    args = parser.parse_args(argv)

    src = Path(args.src).expanduser().resolve()
    try:
        if args.home:
            dest = install_versioned(
                Path(args.home).expanduser(), src,
                channel=args.channel, sha=args.sha,
                built_at=args.built_at, edition=args.edition)
            print(f"installed {dest} and switched current onto it")
        else:
            dest = build_engine_tree(
                src, Path(args.dest).expanduser(),
                channel=args.channel, sha=args.sha,
                built_at=args.built_at, edition=args.edition)
            print(f"built engine tree at {dest}")
    except (RuntimeError, ValueError) as exc:
        print(f"ren package-engine: refused - {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
